
services:
  secure-web:
    image: registry.cn-hangzhou.aliyuncs.com/hook-docker/secure-web:latest
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./safety.db:/app/safety.db
      - ./.env:/app/.env
    environment:
      - DEBUG=false
      - DATABASE_URL=sqlite+aiosqlite:///./safety.db
      - ZHIPU_API_KEY=your-api-key  # 需要替换为实际的API key
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge 